version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: horizons_postgres_dev
    environment:
      POSTGRES_DB: horizons_db
      POSTGRES_USER: horizons_user
      POSTGRES_PASSWORD: horizons_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U horizons_user -d horizons_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_dev:
